version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.3.0
  aws-cli: circleci/aws-cli@2.1.0
  slack: circleci/slack@4.9.3

jobs:
  go-build:
    docker:
      - image: circleci/golang:1.17
    steps:
      - checkout
      - run:
          name: Run tests
          command: go test -v  -covermode=count ./...
          working_directory: lambda
      - run:
          name: Build Binary
          command: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -v -o build_artifact_bin
          working_directory: lambda
      - persist_to_workspace:
          root: .
          paths:
            - lambda/build_artifact_bin
  ecr-build-and-deploy:
    executor: aws-ecr/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - aws-ecr/build-and-push-image:
          repo: $AWS_ECR_REPOSITORY
          tag: "${CIRCLE_SHA1},latest"
          path: lambda
          checkout: false
  lambda-func-update:
    executor: aws-cli/default
    steps:
      - aws-cli/setup
      - run: 
          name: Update Lambda Function Image
          command: aws lambda update-function-code --region $AWS_REGION --function-name $AWS_LAMBDA_FUNCTION --image-uri ${AWS_ECR_ACCOUNT_URL}/${AWS_ECR_REPOSITORY}:latest
  notify:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - slack/notify:
          template: success_tagged_deploy_1
  github-build-and-push:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - run:
          name: GHCR Login
          command: echo $GHCR_PAT | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      - run:
          name: Build Image
          working_directory: k8s
          command: |
            IMAGE_TAG="$(git tag -l v* --sort=authordate | tail  -n 1)"
            echo Image Tag $IMAGE_TAG
            docker build -t $GHCR_REPOSITORY:$IMAGE_TAG -f Dockerfile.arm64 .
            docker tag $GHCR_REPOSITORY:$IMAGE_TAG $GHCR_REPOSITORY:latest
            docker push $GHCR_REPOSITORY:$IMAGE_TAG
            docker push $GHCR_REPOSITORY:latest
      - run:
          name: GHCR Logout
          command: docker logout
    
workflows:
  version: 2
  aws-lambda-deploy:
    jobs:
      - go-build:
          filters:
            tags:
              only: /^lambda\/v[0-9]+(\.[0-9]+)*$/
            branches:
              only: main
      - ecr-build-and-deploy:
          context: aws-env
          filters:
            tags:
              only: /^lambda\/v[0-9]+(\.[0-9]+)*$/
            branches:
              only: main
          requires:
            - go-build
      - lambda-func-update:
          context: aws-env
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^lambda\/v[0-9]+(\.[0-9]+)*$/
          requires:
            - ecr-build-and-deploy
      - notify: 
          context: slack-env
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^lambda\/v[0-9]+(\.[0-9]+)*$/
          requires:
            - lambda-func-update
  arm64-image-build:
    jobs:
      - github-build-and-push:
          context: github-env
          filters:
            tags:
              only: /^k8s\/v[0-9]+(\.[0-9]+)*$/
            branches:
              ignore: /.*/
      - notify: 
          context: slack-env
          filters:
            tags:
              only: /^k8s\/v[0-9]+(\.[0-9]+)*$/
            branches:
              ignore: /.*/
          requires:
            - github-build-and-push