apiVersion: v1
kind: Namespace
metadata:
  name: hdb
  labels:
    name: hdb

---

apiVersion: v1
kind: Secret
metadata:
  name: hdb-secrets
  namespace: hdb
data:
  TSL_MQTT_USER: xxx
  TSL_MQTT_PASSWORD: xxx
  LOGZIO_TOKEN: xxx
  AWS_ACCESS_KEY_ID: xxx
  AWS_SECRET_ACCESS_KEY: xxx

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: hdb-datasource-indoorclimate
  namespace: hdb
  labels:
    app: hdb-datasource-indoorclimate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hdb-datasource-indoorclimate
  template:
    metadata:
      labels:
        app: hdb-datasource-indoorclimate
    spec:
      volumes:
        - name: secret-volume
          secret:
            secretName: hdb-secrets
      containers:
        - name: hdb-datasource-indoorclimate
          image: ghcr.io/tommzn/hdb-datasource-indoorclimate/arm64:latest
          volumeMounts:
            - name: secret-volume
              mountPath: /run/secrets/token
              readOnly: true
          imagePullPolicy: Always
          env:
            - name: GO_CONFIG_S3_BUCKET
              value: <config bucket>
            - name: GO_CONFIG_S3_KEY
              value: <path to config file>
            - name: AWS_REGION
              value: eu-west-1