name: Image Build
on:
  create:
    tags:
      - k8s/v*

jobs:
  go-build:
    name: Go Binary & Image Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
      - name: Set output
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set output
        run: |
          echo $RELEASE_VERSION
          echo $GITHUB_REF
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get Go version
        run: echo "goversion=`egrep -i '^go [1-2][.][0-9]+$' go.mod | sed 's/go //' | sed 's/$/.x/'`" >> $GITHUB_ENV
        working-directory: ./k8s
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.goversion }}
      - name: Build Binary
        run: CGO_ENABLED=0 GOOS=linux GOARCH=${{ matrix.arch }} go build -a -installsuffix cgo -v -o build_artifact_bin
        working-directory: ./k8s
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - name: Build Image
        uses: docker/build-push-action@v2
        with:
          context: ./k8s
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/_${{ matrix.arch }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}_${{ matrix.arch }}:latest
  
        